language: cpp
dist: bionic

matrix:
  include:
   - os: linux
     arch: s390x
     compiler: gcc
     env:
       - COMPILER=g++
       - COMP=gcc

branches:
  only:
   - master

before_script:
  - cd src

script:
  # Download net
  - make net

  # Obtain bench reference from git log
  - git log HEAD | grep "\b[Bb]ench[ :]\+[0-9]\{7\}" | head -n 1 | sed "s/[^0-9]*\([0-9]*\).*/\1/g" > git_sig
  - export benchref=$(cat git_sig)
  - echo "Reference bench:" $benchref

  #
  # Compiler version string
  - $COMPILER -v

  #
  # Verify bench number against various builds
  - make clean && make -j2 ARCH=general-64 build && ../tests/signature.sh $benchref
