language: cpp
dist: bionic

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['g++-8', 'g++-8-multilib', 'g++-multilib', 'valgrind', 'expect', 'curl']
      env:
        - CXX=g++-8
        - CC=gcc

    - os: linux
      compiler: clang
      addons:
        apt:
          packages: ['clang-10', 'llvm-10-dev', 'g++-multilib', 'valgrind', 'expect', 'curl']
      env:
        - CXX=clang++-10
        - CC=clang

    - os: osx
      osx_image: xcode12
      compiler: gcc
      env:
        - CXX=g++
        - CC=gcc

    - os: osx
      osx_image: xcode12
      compiler: clang
      env:
        - CXX=clang++
        - CC=clang

branches:
  only:
   - master

script:
  # Compiler version string
  - $CXX -v

  # Run Travis-specific tests
  - ./tests/travis.sh
