version: 1.0.{build}
clone_depth: 50

branches:
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2019

# Build platform, i.e. x86, x64, AnyCPU. This setting is optional.
platform:
  - x86
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

matrix:
  # The build fail immediately once one of the job fails
  fast_finish: true

# Scripts that are called at very beginning, before repo cloning
init:
  - cmake --version
  - msbuild /version

before_build:
  - ps: |
      # Obtain bench reference from git log
      $b = git log HEAD | sls "\b[Bb]ench[ :]+[0-9]{7}" | select -first 1
      $bench = $b -match '\D+(\d+)' | % { $matches[1] }
      Write-Host "Reference bench:" $bench
      $g = "Visual Studio 16 2019"
      If (${env:PLATFORM} -eq 'x64') { $a = "x64" }
      If (${env:PLATFORM} -eq 'x86') { $a = "Win32" }
      cmake -G "${g}" -A ${a} -B build .
      Write-Host "Generated files for: " $g $a

build_script:
  - cmake --build build --config %CONFIGURATION% -- /verbosity:minimal

before_test:
  - cd build
  - stockfish bench 2> out.txt >NUL
  - ps: |
      # Verify bench number
      $s = (gc "./out.txt" | out-string)
      $r = ($s -match 'Nodes searched \D+(\d+)' | % { $matches[1] })
      Write-Host "Engine bench:" $r
      Write-Host "Reference bench:" $bench
      If ($r -ne $bench) { exit 1 }
