name: Stockfish
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  Binaries:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/stockfish_binaries.yml
